### ISSUE TITLE
(Session 9, 1) Add feature: Sending Cheeps

### ISSUE THREAD

**Issue by llucitu** [ITU-BDSA2024-GROUP19/Chirp#120]
As a logged-in user, I want to add "cheeps" so that I can express an opinion on the Chirp website.

Acceptance criteria:
- The user shouldn't be able to send cheeps if they are not registered or logged in.
- The cheep should appear on both the public and the user's personal timeline.
- A message should displays if the cheep is longer than 160 characters.
- Add UI tests for the cheep box and length constraints.

**Comment by Spon-art** [comment]
This feature has been implemented yesterday by the 4 assigness. Good work guys. I hereby declare this issue closed.
