### ISSUE TITLE
Create and expand on test library

### ISSUE THREAD

**Issue by RonoITU** [ITU-BDSA2024-GROUP19/Chirp#133]
We once again have a folder `test` separately from `src`. For each package of the Onion model, have a test package. 

Acceptance Criteria:
- `Chirp.Core` is covered by test package `Chirp.Core.Test`
- `Chirp.Web` is covered by test package `Chirp.Web.Test`

**Comment by RonoITU** [comment]
I created a `Chirp.Web` test library yesterday, merging onto main today. This is ongoing work as more things to test come up.

**Comment by RonoITU** [comment]
- I want us to do an XSS test: Trying to post a Cheep containing a script to the database. See if we can automate this.

**Comment by NewNorthStar** [comment]
- I want us to make an SQL injection test: Trying to post a cheep containing a script to alter the database.
