### ISSUE TITLE
Add account registration to the infrastructure layer. 

### ISSUE THREAD

**Issue by RonoITU** [ITU-BDSA2024-GROUP19/Chirp#150]
In order to solve issue #149, we want the ability to register an account (interacting with `UserManager`, checking for duplicates, emailing the user, etc.) to be part of the infrastructure layer. This requires a refactor of the code currently in the scaffold for the Identity system. 

## Acceptance Criteria:

- Make a new interface and implementation `IChirpAccountRepository` and `IChirpAccountService` for the methods to reside in. 
- Analyse the code found in `src\Chirp.Web\Areas\Identity\Pages\Account\ExternalLogin.cshtml.cs` and `src\Chirp.Web\Areas\Identity\Pages\Account\Register.cshtml.cs` that registers a user. 
- Make a similar implementation in the new infrastructure classes. For this ticket, it should work in the same way. 
- The service should be responsible for assembling the user object to be added. 
- The repository should be responsible for entering the user into the database. 
- Continue to use the build in `UserManager` and `SignInManager` to the extent possible.

**Comment by Spon-art** [comment]
This was adressed by pull-request #157 . With limited succes, as there are quite high dependence on identity.
