### ISSUE TITLE
2.b. Automatic Releases Clients

### ISSUE THREAD

**Issue by Spon-art** [ITU-BDSA2024-GROUP19/Chirp#46]
Just as in 2.a the Client also needs to automated as well. This should ensure always up-todate code on that part as well. Also so TA's can check up upon us.

Check issue 2.a first or collaborate on this task.

**Comment by RonoITU** [comment]
The web app is now running on Azure. It would now be desirable to clean up and release a new web-only client as v1.0.0 (Breaking with old features)

**Comment by RonoITU** [comment]
I have made an extensive cleanup effort on branch `2b-auto-release`. Please continue revise of client here.
