### ISSUE TITLE
Clean-up code from local implementation

### ISSUE THREAD

**Issue by jakso535** [ITU-BDSA2024-GROUP19/Chirp#56]
As developers we need to update our code, removing previous functionallity, as we now use a web service causing the previous code to be outdated.

Acceptance criteria:

- Remove all functionallity not using our web app
- Clean up newly added code where needed
- Ensure the new functionallity still works as intended

**Comment by Spon-art** [comment]
This has been done and reviewed by jakso535 and llucitu
