### ISSUE TITLE
1.b) Add pagination of cheeps

### ISSUE THREAD

**Issue by jakso535** [ITU-BDSA2024-GROUP19/Chirp#64]
As a user it is important for the web app to run efficiently, hence we don't want all cheeps to be displayed at the same time. Therefore we need to implement pagination of cheeps in our razor page web app. 

Acceptance criteria:

- a GET request to a specific page, for example "page=12" should return the 12th page of cheeps from public timeline.
- a page of cheeps needs to be 32 cheeps long.
-  a GET request to a specific page + user, for example "Jakob?page=12, should return the 12th page of all Jakob's cheeps.
- If no page parameter is set, the first page of the public timeline should be displayed.

**Comment by RonoITU** [comment]
Has this been taken care of by pull request #80 ?

**Comment by jakso535** [comment]
> Has this been taken care of by pull request #80 ?

Yes it has.
