### ISSUE TITLE
Task 2.b - SimpleDB database as a separate library project. 

### ISSUE THREAD

**Issue by RonoITU** [ITU-BDSA2024-GROUP19/Chirp#7]
As a database manager, I want a simple CSV based database for storing cheeps. This will allow us to work on database features separately. 
## Acceptance Criteria
- Project contains a new `classlib` called `SimpleDB`. 
- This database uses a CSV library to store Cheeps. 
- Program should be able to `POST` a Cheep to the DB. 
- Program should be able to `GET` a collection of the Cheeps. 
- The record class `Cheep` is used when transferring data.

**Comment by jakso535** [comment]
Missing feature to store cheeps on CSV file.
